### ISSUE TITLE
links 404

### ISSUE THREAD

**Issue by mr-rooftop** [CosmWasm/cw-awesome#10]
Hey guys the links below aren't working:

> cw721-base: This is a basic implementation of a cw721 NFT spec.

https://github.com/CosmWasm/cw-plus/tree/main/contracts/cw721-base
https://github.com/CosmWasm/cw-plus/blob/main/packages/cw721/README.md

**Comment by ethanfrey** [comment]
Good call... moved to github.com/CosmWasm/cw-nft

**Comment by ethanfrey** [comment]
@orkunkl are you maintaining this repo? shall I? shall we more to interwasm DAO?

**Comment by orkunkl** [comment]
@ethanfrey  Makes sense, lets move it to DAO. We will maintain this repo

**Comment by orkunkl** [comment]
Also maybe better rename the repo to `cw-awesome`?

**Comment by ethanfrey** [comment]
sounds good. I will move this afternoon

**Comment by ethanfrey** [comment]
Just transferred.

@orkunkl , want to fix this (and maybe freshen the whole repo)?

**Comment by orkunkl** [comment]
We will take care of that.

**Comment by mikedotexe** [comment]
Addressed some of these concerns in #12
